language: haskell

ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8

os:
  - linux
  - osx

before_script:
  - ghc-pkg list
  - cabal sandbox init
  - cabal install --only-dependencies
  - ghc-pkg list

script:
  - cabal configure --ghc-option=-Werror
  - cabal build

notifications:
  - email: false
