
# Use new container infrastructure to enable caching
sudo: required

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- git clone https://github.com/Daniel-Diaz/stackage-multibuild.git
- cd stackage-multibuild && stack install

script:
# Build the package, its tests, and its docs and run the tests
- stackage-multibuild

# notifications:
#   - email: false
